app:
 audioStorage: target/audio/
 profileScript: target/script-resources/profile_master.sh
 tweetsScript: target/script-resources/tweets.sh
 videoScript: target/script-resources/video.sh
 cleanUpScript: target/script-resources/clean_up.sh
 frameScript: target/script-resources/video_service/master.sh
 masterVideoScript: target/script-resources/video_service/video.sh
 
server:
 port: 8070
  
keycloak:
  realm: breo-realm
  auth-server-url: http://ec2-35-172-117-196.compute-1.amazonaws.com:8080/auth
  resource: video_rest_api
  ssl-required: none
  bearer-only: true
  credentials:
    secret: cf4d3cb0-dc6e-42ca-93ed-7a7df5a0e39f
  use-resource-role-mappings: false
  confidential-port: 0 
